#                  Community Bridge Configuration File
# -----------------------------------------------------------------------------

#                             General Settings
# -----------------------------------------------------------------------------
# Log level controls the degree of detail that is sent to the console/log
# The possible settings are (in order of quietest to noisiest:
#   info, config, fine, finer, finest, all
# - During configuration, I recommend using 'config'.
# - During normal operation, I recommend using 'info'.
# - If you want to see the notifications that the synchronize and reminder
#   notices have been sent, use 'fine'
# - During troubleshooting of problems, set this to either finest or all.
log-level: config

# Allow plugin metrics to start up for this plugin.
# Disable for all plugins by editing the plugins/PluginMetrics/config.yml file.
# They can be viewed at: http://mcstats.org
plugin-metrics: true

# Set the unit of measurement for sync and reminder scheduling. Options are:
# ticks, seconds, minutes, or hours. Note that this applies to both
# auto-sync-every and auto-remind-every.
auto-every-unit: minutes

# This is a timer that will check and sync all data with your database at a set
# interval. Otherwise group and player statistics will only be synchronized when
# they join and leave the server.
auto-sync: true

# The interval for the auto-sync timer, this should not be set any lower than
# 20 minutes.
auto-sync-every: 20

#                             Database Settings
# -----------------------------------------------------------------------------
# Please ensure if you run your Minecraft server on a remote host
# that your MySQL server allows REMOTE connections. This WILL NOT WORK unless
# your MySQL server is configured to allow connections from the machine that
# your Minecraft server is running on. If you don't know what that means, consult
# your hosting provider on how to configure your MySQL server correctly.
# All of this information should be the same server and database used by your
# web-application...
database:
  # Hostname for your MySQL Server
  hostname: localhost

  # MySQL Port
  port: 3306

  # Database Name
  name: databasename

  # Database Username
  username: username

  # Database Password
  password: password

#                             Player Linking Settings
# -----------------------------------------------------------------------------
# Settings associated with linking a Minecraft player with a web application's
# user. As this feature is a prerequisite for all other features, it cannot
# be disabled.
player-user-linking:
  # If you want the player disconnected from the game if they haven't
  # registered, then set this to true. They will be shown the
  # link-unregistered-player message (in message.yml) on the disconnected
  # screen.
  kick-unregistered: false

  # This is a timer that will notify unregistered users to register every few
  # minutes.
  auto-remind: true

  # The interval for the auto-remind timer, this should be no less than
  # 5-10 minutes. Note that this uses the units specified above in
  # auto-every-unit.
  auto-remind-every: 10

  # Set these to true to inform players when they log in if they're linked to
  # the web application. These correspond to the link-unregistered-player and
  # link-registered-player messages in messages.yml.
  notify-registered-player: true
  notify-unregistered-player: true

  # This is where we specify how to associate a Minecraft player with a web
  # application user. We do this by matching up the player name with a name
  # stored in the web application's database.
  #
  # If you want your players to use the same name on both the server and the
  # web application, then you will need to provide the table and column
  # information where the web application relates its user IDs with the user's
  # name/login ID/login/username.
  #
  # If you want to allow them to use a different name on the web application,
  # you need to add a custom field or column to your web application's database,
  # and provide that table and column information here.

  # The name of the table which contains the columns:
  table-name: ''

  # Column on the table that contains the user ID. Typically something like
  # user_id or member_id
  user-id-column: ''

  # If the player name is stored in a key-value pair of columns instead of
  # its own column, set this to true:
  uses-key: false

  # If you set 'linking-uses-key' to false, then set this to the column that
  # the playername is stored in. Otherwise, leave it empty.
  playername-column: ''

  # If you set 'linking-uses-key' to true, then set the key column, value column,
  # and the key-name here. Otherwise, leave these fields empty.
  key-name: ''
  key-column: ''
  value-column: ''

# -----------------------------------------------------------------------------
#OLD

# This is a timer that will notify unregistered users more frequently to
# register
auto-remind: true

# The interval for the auto-remind timer, this should be no less than
# 5-10 minutes.
auto-remind-every: 10

# This message is displayed when show-primary-group is false to registered users
registered-message: Registered Account, Linked to Server Forums

# This is shown to users when they connect that arn't registered
unregistered-message: Unregistered Account - Please Register at YOURFORUMURL for full access

# This is shown when auto-sync runs to remind a user to register
unregistered-messagereminder: Just a reminder to visit YOURFORUMURL and register today!

# When true this will not allow un-registered players onto the server, and show
# the unregistered-message in the form of a kick
kick-unregistered: false

# The permissions system (PEX, bPerms, GroupManager, PermsBukkit)
permissions-system: PEX

# If set to true it will show a message to the user that they have been placed
# into a group
show-primary-group: true

# Multi-Tables are when you have all your tracking/minecraft usernames in a
# different table to the users table
multi-tables: false

# Forums like XenForo use a table that has rows for each custom field as opposed
# to columns for each custom field
multi-tables-use-key: false

# If set to true it will not allow banned players from your website to connect
use-banned-field: false

# Ban List in Seperate Table (Such as PHPBB) If you include a value for reason
# then it will display that when booting the player
banlist-table:
    enabled: false
    table: phpbb_banlist
    user-id-field: ban_userid
    reason-field: ban_reason

# Eventually, all settings related to group synchronization will reside here.
group-synchronization:
  primary-group:
    enabled: true
    # If a user's group ID on the web application side is on this list, it
    # won't be synchronized. Example: ['1','2','3','115']. [] is an empty list.
    group-ids-to-ignore: []

    # If a player's group name is on this list the web application group won't
    # be synchronized over it. (NOT YET IMPLEMENTED)
    group-names-to-ignore: []

# Groups in Separate Table (Such as PHPBB)
groups-table:
    enabled: false
    table: phpbb_users_groups
    user-id-field: ban_userid
    group-id-field: ban_reason

# If you have a second group level and want to make use of it
secondary-groups: false

# This is for extra features of the bridge plugin that allow you to save age,
# gametime, last online, health, etc. to the database
enable-basic-tracking: false

#
# Main Users table configuration
#
users-table:
  # Users Database Table
  table: ipbog3members

  # The field that contains their Minecraft Username
  user-name-field: username

  # The field that contains their Unique ID across your site
  user-id-field: member_id

  # The field that contains their Primary Group
  groups-id-field: member_group_id

  # The field that contains their Secondary Group
  secondary-groups-id-field: sub_group_ids

  # The Banned Field should be a 1 or 0
  banned-field: member_banned

  # The Group Banned Users are placed in on your site
  banned-users-group: 5

  # The Default Group for when a group can't be found or they are unregistred.
  # Note that this is the group ID on the web application, not the permissions
  # group name.
  default-group: 2

#
# This is only for multi-table websites where information is not all contained
# in the users table
#
multi-table:

  # Table that contains custom information for MineCraft
  table: ipbog3pfields_content

  # The field that has their users id
  field-user-id-field: member_id

  # This is the field that contains the KEY for multi-tables-use-key (XenForo)
  field-key-field: key_str

  # The value that is to be matched in field-key-field when looking for their
  # Minecraft Username
  field-key-value: mcusername

  # This is for when multi-tables-use-key is false (Invision Power Board) it
  # contains their Minecraft Username
  field-value-field: field_11


#
# Optional
# You can place users in the default group if they do not have an Avatar or
# Minimum Posts or both
#

profile-requirements:

  # Enable Forced Website Avatar
  require-avatar: false

  # Message when Avatar Not Found
  require-avatar-message: This server requires players to upload an avatar to their profile.

  # Table that contains user avatars
  require-avatar-table: ipbog3profile_portal

  # Field that has their User ID
  require-avatar-user-id-field: member_id

  # Field that has their Avatar (Empty/null value for no avatar)
  require-avatar-field: pp_main_photo

  # Enable Forced Minimum Posts
  require-minposts: false

  # Messages when Minimum Posts not met
  require-minposts-message: This server requires players to have a minimum of 3 forum posts.

  # Required amount of minimum Posts
  require-minposts-count: 3

  # Table that contains their post count
  require-minposts-table: ipbog3members

  # Field that has their User ID
  require-minposts-user-id-field: member_id

  # Field that has their post count
  require-minposts-field: posts


#
# Optional
# This is for Online Status, Health, Age etc...
#

basic-tracking:

  # Table that contains the custom fields
  table: ipbog3pfields_content

  # Enable Tracking of Online status
  field-onlinestatus-enabled: true

  # Value to place in table when online
  field-onlinestatus-valueonline: 1

  # Value to place in table when offline
  field-onlinestatus-valueoffline: 0

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-onlinestatus-key-value: mconlinestatus

  # Multi-Tables / Single Table field for Value
  field-onlinestatus-field: field_14

  # Enable tracking if player is online or not
  field-lastonline-enabled: true

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-lastonline-key-value: mclastonline

  # Multi-Tables / Single Table field for Value
  field-lastonline-field: field_15

  # If you want to have a profile field that contains the gametime expressed
  # in words (5 hours, 33 minutes...), create the custom field on your forum
  # and enter its name here. Otherwise, leave 'blank': ''
  # Note that for this to work, the field-lastonline-field must also have
  # field/column and be configured correctly.
  field-lastonline-formatted-field: ''

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  # If you want to have a profile field that contains the gametime expressed
  # in words (5 hours, 33 minutes...), create the custom field on your forum
  # and enter its name here. Otherwise, leave 'blank': ''
  # Note that for this to work, the field-lastonline-key-value must also have
  # field/column and be configured correctly.
  field-lastonline-formatted-key-value: ''

  # Enable tracking how much time is spent on server
  # Note: This relies on 'lastonline' being enabled to work.
  field-gametime-enabled: true

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-gametime-key-value: mcgametime

  # Multi-Tables / Single Table field for Value
  field-gametime-field: field_16

  # If you want to have a profile field that contains the gametime expressed
  # in words (5 hours, 33 minutes...), create the custom field on your forum
  # and enter its name here. Otherwise, leave 'blank': ''
  # Note that for this to work, the field-gametime-field must also be set.
  field-gametime-formatted-field: ''

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  # If you want to have a profile field that contains the gametime expressed
  # in words (5 hours, 33 minutes...), create the custom field on your forum
  # and enter its name here. Otherwise, leave 'blank': ''
  # Note that for this to work, the field-gametime-key-value must also be set.
  field-gametime-formatted-key-value: ''

  # Enable Total XP earnt tracking
  field-totalxp-enabled: true

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-totalxp-key-value: mctotalxp

  # Multi-Tables / Single Table field for Value
  field-totalxp-field: field_18

  # Enable Current XP tracking (progress to next level)
  field-currentxp-enabled: true

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-currentxp-key-value: mccurrentxp

  # Multi-Tables / Single Table field for formatted version.
  field-currentxp-formatted-field: ''

  # Multi-Tables-Use Key 'field' for formatted version.
  field-currentxp-formatted-key-value: ''

  # Multi-Tables / Single Table field for Value
  field-currentxp-field: field_17

  # Enable Level tracking
  field-level-enabled: true

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-level-key-value: mclevel

  # Multi-Tables / Single Table field for Value
  field-level-field: field_19

  # Enable tracking of players health
  field-health-enabled: true

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-health-key-value: mchealth

  # Multi-Tables / Single Table field for Value
  field-health-field: field_20

  # Enable tracking of players time alive since last death
  field-lifeticks-enabled: true

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-lifeticks-key-value: mclifeticks

  # Multi-Tables / Single Table field for Value
  field-lifeticks-field: field_21

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-lifeticks-formatted-key-value: ''

  # Multi-Tables / Single Table field for Value
  field-lifeticks-formatted-field: ''

  # Enable Wallet Tracking (NOT IN USE YET)
  field-wallet-enabled: false

  # Multi-Tables-Use-Key value for multi-tables.field-key-field
  field-wallet-key-value: mcwallet

  # Multi-Tables / Single Table field for Value
  field-wallet-field: field_23

#
# Group Configuration
# The strings on the left ('1', '2', etc.) is the group ID in the web application's
# mysql database, the string on the right is the group name in your permissions
# system.
#
groups:
  '1': validating
  '2': guest
  '3': builder
  '6': moderator
  '4': admin
  '5': banned
